version: "3"
services:
  mysql:
    container_name: "dstack-mysql"
    image: bitnami/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1388
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1388
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/data:/bitnami/mysql/data

  php:
    container_name: "dstack-php"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./docker/php/php.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro

  apache:
    container_name: "dstack-apache"
    image: bitnami/apache:2.4
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - php
    volumes:
      - ./site:/app
      - ./docker/apache/my_vhost.conf:/vhosts/myapp.conf:ro

  phpmyadmin:
    container_name: "dstack-phpmyadmin"
    image: bitnami/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - '81:8081'
      - '8143:8444'
    environment:
      - DATABASE_HOST=host.docker.internal
volumes:
  dstack-mysql:
    driver: local